### ISSUE TITLE
How can I use this package?

### ISSUE THREAD

**Issue by onesup** [namiwang/actioncable_dart#1]
I am a ruby web programmer.
I found this one in `pub.dev` .
But I don't know how to use this exactly.
Can you build super simple example even without rails server?

Thank you Namiwang.

**Comment by namiwang** [comment]
@onesup 

Yeah, I should coin some examples.

For now, there's some simple usage in README.

A basic one would be like

```
import 'package:action_cable/action_cable.dart';

cable = ActionCable.Connect(
  'ws://127.0.0.1:3000/cable',
  headers: {
    'Authorization': 'Some Token',
  },

  onConnected: (){
    print('connected');
  },
);
```
